-- Catálogo geográfico: países.
-- Datos precargados y de solo lectura para la API (no hay ABM de países).
-- Es idempotente: se puede ejecutar varias veces.
-- Fuente: https://github.com/dr5hn/countries-states-cities-database (json/countries+states+cities.json)
-- Campo codigo_iso = ISO 3166-1 alpha-3. Campo nombre = traducción al español de la fuente.
INSERT IGNORE INTO paises (nombre, codigo_iso) VALUES
    ('Afganistán', 'AFG'),
    ('Alandia', 'ALA'),
    ('Albania', 'ALB'),
    ('Alemania', 'DEU'),
    ('Andorra', 'AND'),
    ('Angola', 'AGO'),
    ('Anguilla', 'AIA'),
    ('Antártida', 'ATA'),
    ('Antigua y Barbuda', 'ATG'),
    ('Arabia Saudí', 'SAU'),
    ('Argelia', 'DZA'),
    ('Argentina', 'ARG'),
    ('Armenia', 'ARM'),
    ('Aruba', 'ABW'),
    ('Australia', 'AUS'),
    ('Austria', 'AUT'),
    ('Azerbaiyán', 'AZE'),
    ('Bahamas', 'BHS'),
    ('Bahrein', 'BHR'),
    ('Bangladesh', 'BGD'),
    ('Barbados', 'BRB'),
    ('Bélgica', 'BEL'),
    ('Belice', 'BLZ'),
    ('Benín', 'BEN'),
    ('Bermudas', 'BMU'),
    ('Bielorrusia', 'BLR'),
    ('Bolivia', 'BOL'),
    ('Bonaire, Sint Eustatius and Saba', 'BES'),
    ('Bosnia y Herzegovina', 'BIH'),
    ('Botswana', 'BWA'),
    ('Brasil', 'BRA'),
    ('Brunei', 'BRN'),
    ('Bulgaria', 'BGR'),
    ('Burkina Faso', 'BFA'),
    ('Burundi', 'BDI'),
    ('Bután', 'BTN'),
    ('Cabo Verde', 'CPV'),
    ('Camboya', 'KHM'),
    ('Camerún', 'CMR'),
    ('Canadá', 'CAN'),
    ('Catar', 'QAT'),
    ('Chad', 'TCD'),
    ('Chile', 'CHL'),
    ('China', 'CHN'),
    ('Chipre', 'CYP'),
    ('Colombia', 'COL'),
    ('Comoras', 'COM'),
    ('Congo', 'COG'),
    ('Congo (Rep. Dem.)', 'COD'),
    ('Corea del Norte', 'PRK'),
    ('Corea del Sur', 'KOR'),
    ('Costa de Marfil', 'CIV'),
    ('Costa Rica', 'CRI'),
    ('Croacia', 'HRV'),
    ('Cuba', 'CUB'),
    ('Curaçao', 'CUW'),
    ('Dinamarca', 'DNK'),
    ('Dominica', 'DMA'),
    ('Ecuador', 'ECU'),
    ('Egipto', 'EGY'),
    ('El Salvador', 'SLV'),
    ('Emiratos Árabes Unidos', 'ARE'),
    ('Eritrea', 'ERI'),
    ('Eslovenia', 'SVN'),
    ('España', 'ESP'),
    ('Estados Unidos', 'USA'),
    ('Estonia', 'EST'),
    ('Etiopía', 'ETH'),
    ('Filipinas', 'PHL'),
    ('Finlandia', 'FIN'),
    ('Fiyi', 'FJI'),
    ('Francia', 'FRA'),
    ('Gabón', 'GAB'),
    ('Gambia', 'GMB'),
    ('Georgia', 'GEO'),
    ('Ghana', 'GHA'),
    ('Gibraltar', 'GIB'),
    ('Grecia', 'GRC'),
    ('Grenada', 'GRD'),
    ('Groenlandia', 'GRL'),
    ('Guadalupe', 'GLP'),
    ('Guam', 'GUM'),
    ('Guatemala', 'GTM'),
    ('Guayana Francesa', 'GUF'),
    ('Guernsey', 'GGY'),
    ('Guinea', 'GIN'),
    ('Guinea Ecuatorial', 'GNQ'),
    ('Guinea-Bisáu', 'GNB'),
    ('Guyana', 'GUY'),
    ('Haiti', 'HTI'),
    ('Honduras', 'HND'),
    ('Hong Kong', 'HKG'),
    ('Hungría', 'HUN'),
    ('India', 'IND'),
    ('Indonesia', 'IDN'),
    ('Irak', 'IRQ'),
    ('Iran', 'IRN'),
    ('Irlanda', 'IRL'),
    ('Isla Bouvet', 'BVT'),
    ('Isla de Man', 'IMN'),
    ('Isla de Navidad', 'CXR'),
    ('Isla de Norfolk', 'NFK'),
    ('Islandia', 'ISL'),
    ('Islas Caimán', 'CYM'),
    ('Islas Cocos o Islas Keeling', 'CCK'),
    ('Islas Cook', 'COK'),
    ('Islas Faroe', 'FRO'),
    ('Islas Georgias del Sur y Sandwich del Sur', 'SGS'),
    ('Islas Heard y McDonald', 'HMD'),
    ('Islas Malvinas', 'FLK'),
    ('Islas Marianas del Norte', 'MNP'),
    ('Islas Marshall', 'MHL'),
    ('Islas Pitcairn', 'PCN'),
    ('Islas Salomón', 'SLB'),
    ('Islas Svalbard y Jan Mayen', 'SJM'),
    ('Islas Tokelau', 'TKL'),
    ('Islas Turks y Caicos', 'TCA'),
    ('Islas Ultramarinas Menores de Estados Unidos', 'UMI'),
    ('Islas Vírgenes de los Estados Unidos', 'VIR'),
    ('Islas Vírgenes del Reino Unido', 'VGB'),
    ('Israel', 'ISR'),
    ('Italia', 'ITA'),
    ('Jamaica', 'JAM'),
    ('Japón', 'JPN'),
    ('Jersey', 'JEY'),
    ('Jordania', 'JOR'),
    ('Kazajistán', 'KAZ'),
    ('Kenia', 'KEN'),
    ('Kirguizistán', 'KGZ'),
    ('Kiribati', 'KIR'),
    ('Kosovo', 'XKX'),
    ('Kuwait', 'KWT'),
    ('Laos', 'LAO'),
    ('Lesotho', 'LSO'),
    ('Letonia', 'LVA'),
    ('Líbano', 'LBN'),
    ('Liberia', 'LBR'),
    ('Libia', 'LBY'),
    ('Liechtenstein', 'LIE'),
    ('Lituania', 'LTU'),
    ('Luxemburgo', 'LUX'),
    ('Macao', 'MAC'),
    ('Macedonia del Norte', 'MKD'),
    ('Madagascar', 'MDG'),
    ('Malasia', 'MYS'),
    ('Malawi', 'MWI'),
    ('Maldivas', 'MDV'),
    ('Mali', 'MLI'),
    ('Malta', 'MLT'),
    ('Marruecos', 'MAR'),
    ('Martinica', 'MTQ'),
    ('Mauricio', 'MUS'),
    ('Mauritania', 'MRT'),
    ('Mayotte', 'MYT'),
    ('México', 'MEX'),
    ('Micronesia', 'FSM'),
    ('Moldavia', 'MDA'),
    ('Mónaco', 'MCO'),
    ('Mongolia', 'MNG'),
    ('Montenegro', 'MNE'),
    ('Montserrat', 'MSR'),
    ('Mozambique', 'MOZ'),
    ('Myanmar', 'MMR'),
    ('Namibia', 'NAM'),
    ('Nauru', 'NRU'),
    ('Nepal', 'NPL'),
    ('Nicaragua', 'NIC'),
    ('Níger', 'NER'),
    ('Nigeria', 'NGA'),
    ('Niue', 'NIU'),
    ('Noruega', 'NOR'),
    ('Nueva Caledonia', 'NCL'),
    ('Nueva Zelanda', 'NZL'),
    ('Omán', 'OMN'),
    ('Países Bajos', 'NLD'),
    ('Pakistán', 'PAK'),
    ('Palau', 'PLW'),
    ('Palestina', 'PSE'),
    ('Panamá', 'PAN'),
    ('Papúa Nueva Guinea', 'PNG'),
    ('Paraguay', 'PRY'),
    ('Perú', 'PER'),
    ('Polinesia Francesa', 'PYF'),
    ('Polonia', 'POL'),
    ('Portugal', 'PRT'),
    ('Puerto Rico', 'PRI'),
    ('Reino Unido', 'GBR'),
    ('República Centroafricana', 'CAF'),
    ('República Checa', 'CZE'),
    ('República de Sudáfrica', 'ZAF'),
    ('República Dominicana', 'DOM'),
    ('República Eslovaca', 'SVK'),
    ('Reunión', 'REU'),
    ('Ruanda', 'RWA'),
    ('Rumania', 'ROU'),
    ('Rusia', 'RUS'),
    ('Sahara Occidental', 'ESH'),
    ('Saint Martin', 'MAF'),
    ('Samoa', 'WSM'),
    ('Samoa Americana', 'ASM'),
    ('San Bartolomé', 'BLM'),
    ('San Cristóbal y Nieves', 'KNA'),
    ('San Marino', 'SMR'),
    ('San Pedro y Miquelón', 'SPM'),
    ('San Vicente y Granadinas', 'VCT'),
    ('Santa Helena', 'SHN'),
    ('Santa Lucía', 'LCA'),
    ('Santa Sede', 'VAT'),
    ('Santo Tomé y Príncipe', 'STP'),
    ('Senegal', 'SEN'),
    ('Serbia', 'SRB'),
    ('Seychelles', 'SYC'),
    ('Sierra Leone', 'SLE'),
    ('Singapur', 'SGP'),
    ('Sint Maarten (Dutch part)', 'SXM'),
    ('Siria', 'SYR'),
    ('Somalia', 'SOM'),
    ('Sri Lanka', 'LKA'),
    ('Suazilandia', 'SWZ'),
    ('Sudán', 'SDN'),
    ('Sudán del Sur', 'SSD'),
    ('Suecia', 'SWE'),
    ('Suiza', 'CHE'),
    ('Surinam', 'SUR'),
    ('Tailandia', 'THA'),
    ('Taiwán', 'TWN'),
    ('Tanzania', 'TZA'),
    ('Tayikistán', 'TJK'),
    ('Territorio Británico del Océano Índico', 'IOT'),
    ('Tierras Australes y Antárticas Francesas', 'ATF'),
    ('Timor Oriental', 'TLS'),
    ('Togo', 'TGO'),
    ('Tonga', 'TON'),
    ('Trinidad y Tobago', 'TTO'),
    ('Túnez', 'TUN'),
    ('Turkmenistán', 'TKM'),
    ('Turquía', 'TUR'),
    ('Tuvalu', 'TUV'),
    ('Ucrania', 'UKR'),
    ('Uganda', 'UGA'),
    ('Uruguay', 'URY'),
    ('Uzbekistán', 'UZB'),
    ('Vanuatu', 'VUT'),
    ('Venezuela', 'VEN'),
    ('Vietnam', 'VNM'),
    ('Wallis y Futuna', 'WLF'),
    ('Yemen', 'YEM'),
    ('Yibuti', 'DJI'),
    ('Zambia', 'ZMB'),
    ('Zimbabue', 'ZWE');
